### ISSUE TITLE
veins_gym

### ISSUE THREAD

**Issue by zjlyy** [ComNetsHH/omnetpp-ml#1]
Hello, I'm asking some questions about veins_gym.

Regarding the Tictoc case you provided, is the whole process compiled through omnet++? I set up successfully through omnet++ with no errors. main.py is then run, but "TimeoutError: veins instance did not send a request within 3.0 seconds" appears.

**Comment by dstolpmann** [comment]
Hi,

the C++ code is compiled as in any other OMNeT++ simulation. However, the Veins-Gym also has a Python module that implements the OpenAI Gym interface and communicates with the OMNeT++ simulation via Protocol Buffers over ZeroMQ. The Python code is not complied, but interpreted, so no rebuild is required when something is changed there.

Based on the error message, I would say that either the OMNeT++ simulation is not started by the Python code or the GymConnection module in the OMNeT++ simulation is not properly initialized.

Best regards
Daniel

**Comment by zjlyy** [comment]
Hi

Thank you for your answer. The previous problem has been solved.

I tried to write a project that used veins_gym, and when the whole project ran several times, In veins_gym step function sometimes due to "assert the self. Observation. The contains (step_tesult.)" assertion mistakes. This error occurs when step() is executed for the first time after reset().

How could I solve the problem?

**Comment by dstolpmann** [comment]
Hi,

I am sorry, but I don't really get your problem.

Can you please try to explain the issue in a bit more detail and maybe provide a screenshot of the error message and/or some example code?

Best regards
Daniel

**Comment by zjlyy** [comment]
Hi

![obs](https://user-images.githubusercontent.com/46021301/232747922-532ead69-9387-4e41-9b9d-91757bf7c37b.png)

This error occurs when the process is run again after the project has successfully run once.

**Comment by dstolpmann** [comment]
Hi,

the error message means that the received observation does not correspond to the observation space. It is hard for me to tell what is going on without the code.

Do you start the OMNeT++ simulation from the Python code or separately? If you start it separately, did you also restart it between runs?

Best regards
Daniel

**Comment by zjlyy** [comment]
Hi

I usually start omnet++ and then execute python code to connect.

When the omnet++ emulation runs, the "step" function in python code returns done (" done=True ") and exits the loop.

This error usually occurs on the second execution, if the "reset" function is able to receive the first "observation", after which the "step" function will have this error.

**Comment by dstolpmann** [comment]
Hi,

Unfortunately, I cannot reproduce the error. Even when I run the OMNeT++ simulation separately, it will always run till the end and then set done to True, because this is done in the destructor of the GymConnection class.  How have you been able to keep the OMNeT++ simulation running?

Is there a particular reason why you start the simulation separately? I think the idea in Veins-Gym is that one episode is equal to one OMNeT++ simulation run. So for each episode, a new simulation is started.

Best regards
Daniel

**Comment by zjlyy** [comment]
Thank you very much for your answer. Due to the time difference, today's conversation will be over.

I will try to rewrite a project later to reproduce this error. Could you please help me solve this problem?

Finally, thank you again for your help!

**Comment by dstolpmann** [comment]
Hi,

yes, I am happy to help with this issue.

Best regards
Daniel

**Comment by melinano** [comment]
> Thank you for your answer. The previous problem has been solved.


Excuse me, would you be so kind and explain how you solved the connection problem? I'm running every time in a timeout. Thanks!

**Comment by dstolpmann** [comment]
Hi,

can you please explain what you did so far? Normally, the Python code should start the OMNeT++ simulation and connect to it.

Best regards
Daniel

**Comment by melinano** [comment]
> Hi,
> 
> can you please explain what you did so far? Normally, the Python code should start the OMNeT++ simulation and connect to it.
> 
> Best regards Daniel

 Well, I installed OMNeT++ 6.0.1 (I hope it'll work with this version) on my Ubuntu 22.04 LTS system. Additionally I installed all the required packages in a conda virtual environment, build the Makefile with `opp_makemake -lzmq -lprotobuf` and ran the main.py from the console. Previous I had a problem with protoc, but after installing protobuf==13.19.0 the error vanished. The python version is 3.11.3.
 
 Maybe I didn't set up the connection in a correct manner.
 
 Thank you for your help!

**Comment by dstolpmann** [comment]
Hi,

I just set up a VM with a similar environment and tried to reproduce the issue. However, everything works fine for me. Can you please send a screenshot of the complete error message?

Best regards
Daniel

**Comment by dstolpmann** [comment]
Did you build the OMNeT++ simulation using `make`? If not, you will get this error message:

![image](https://github.com/ComNetsHH/omnetpp-ml/assets/7644267/698073d8-6a28-4c98-9313-fde13e8b7934)

**Comment by melinano** [comment]
> Did you build the OMNeT++ simulation using `make`? If not, you will get this error message:
> 
> ![image](https://user-images.githubusercontent.com/7644267/245128685-698073d8-6a28-4c98-9313-fde13e8b7934.png)

Yes, I get the exact same error. But what do you mean by 'build the OMNeT++ simulation using 'make' '? Isn't it the `opp_makemake -lzmq -lprotobuf` line?

**Comment by dstolpmann** [comment]
No, after running `opp_makemake`, you have to run `make`. `opp_makemake` generates the Makefile, while `make` executes the commands in the Makefile to build the OMNeT++ simulation binary. Also make sure to run both commands in the `scenario` subfolder of the example.

**Comment by melinano** [comment]
Aaah, thanks!

I get now another error:

`(veins-gym) melinano@TannuTuvanMachine:~/OMNeT++/omnetpp-ml/examples/openai_gym/tictoc/scenario$ make
GymConnection.cc
In file included from GymConnection.h:27,
                 from GymConnection.cc:23:
veinsgym.pb.h:12:2: error: #error This file was generated by a newer version of protoc which is
   12 | #error This file was generated by a newer version of protoc which is
      |  ^~~~~

veinsgym.pb.h:13:2: error: #error incompatible with your Protocol Buffer headers. Please update
   13 | #error incompatible with your Protocol Buffer headers. Please update
      |  ^~~~~

veinsgym.pb.h:14:2: error: #error your headers.
   14 | #error your headers.
      |  ^~~~~

In file included from GymConnection.h:27,
                 from GymConnection.cc:23:
veinsgym.pb.h:26:10: fatal error: google/protobuf/generated_message_bases.h: No such file or directory
   26 | #include <google/protobuf/generated_message_bases.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

make: *** [Makefile:105: ../out/gcc-release/scenario/GymConnection.o] Error 1
`
What protobuf version is recommended?

**Comment by dstolpmann** [comment]
I just update the guide with the command to install the C++ dependencies on Ubuntu 22.04 LTS. I just used:
```
sudo apt-get install libzmq3-dev libprotobuf-dev protobuf-compiler
```
The version of the Protocol Buffers compiler and the library should match. As Ubuntu 22.04 LTS comes with Protocol Buffers version 3.12.4, you should also install the same version of the Protocol Buffers Python package. Also, you should run the `protoc` command before compiling the OMNeT++ simulation binary.

**Comment by melinano** [comment]
I followed your instructions, but it still not worked and I got the same error about the protobuf version as above. I deleted my local copy of the repo and cloned again and followed the docs strictly once more. The example suddenly worked!!!

Thank you very much!

**Comment by dstolpmann** [comment]
You are welcome! :blush:

**Comment by BingkuiLi** [comment]
There is no error in the previous command, but when I run main.py, I get an error, then I delete the "print_veins_stdout" parameter, and I get another error, I hope you can get your guidance, thank you!
![1693103591755](https://github.com/ComNetsHH/omnetpp-ml/assets/20663105/93770d15-7bcc-463d-b635-dd4952b27a43)

**Comment by BingkuiLi** [comment]
There is no error in the previous command, but when I run main.py, I get an error, then I delete the "print_veins_stdout" parameter, and I get another error, I hope I can get your guidance, thank you!
![1693103591755](https://github.com/ComNetsHH/omnetpp-ml/assets/20663105/d8d4ea1b-0293-4917-958d-4d6b3e673de0)

**Comment by dstolpmann** [comment]
Hi,
Which gym version are you using? The guide was tested with gym version 0.24.1. Can you try to install this version, please?

Best regards
Daniel

**Comment by BingkuiLi** [comment]
来信已收到  谢谢！---这是来自QQ邮箱的自动回复邮件。

**Comment by BingkuiLi** [comment]
Thank you very much, your advice is working, thank you!
