### ISSUE TITLE
Files not found

### ISSUE THREAD

**Issue by MKSBarbosa** [ComNetsHH/omnetpp-ml#2]
Hello, 

I am trying to integrate the tensorflow_cc in the omnet++, but the Tensorflow files are not found by the include in the  .cc files.  I tried to insert the configuration inside the makefile as you suggest but, it did not work. When I compile the example in the tensorflow_cc it works, but not in the omnet++. Do you have any suggestions?

**Comment by dstolpmann** [comment]
Hi,

I need some more information to answer your question. Do you use one of the Docker images that I provided or did you install tensorflow_cc natively on your system?

Best regards
Daniel
